/exchanger/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    exchanger_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/exchanger/exchanger_controller:
  ros__parameters:
    joints:
      - elink1_joint
      - elink2_joint
      - elink3_joint
      - elink4_joint
      - elink5_joint
      - elink6_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
