# Default initial positions for engineer's ros2_control fake system

initial_positions:
  left_x_joint: 0
  left_yaw_joint: 0
  left_z_joint: 0
  link1_joint: 0
  link2_joint: 0
  link3_joint: 0
  link4_joint: 0
  link5_joint: 0
  link6_joint: 0
  link7_joint: 0
  right_x_joint: 0
  right_yaw_joint: 0
  right_z_joint: 0