# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - /engineer/boom_controller
    - /engineer/left_controller
    - /engineer/right_controller

  /engineer/boom_controller:
    type: FollowJointTrajectory
    joints:
      - link1_joint
      - link2_joint
      - link3_joint
      - link4_joint
      - link5_joint
      - link6_joint
      - link7_joint
    action_ns: follow_joint_trajectory
    default: true
  /engineer/left_controller:
    type: FollowJointTrajectory
    joints:
      - left_z_joint
      - left_x_joint
      - left_yaw_joint
    action_ns: follow_joint_trajectory
    default: true
  /engineer/right_controller:
    type: FollowJointTrajectory
    joints:
      - right_z_joint
      - right_x_joint
      - right_yaw_joint
    action_ns: follow_joint_trajectory
    default: true