# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    boom_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

boom_controller:
  ros__parameters:
    joints:
      - link1_joint
      - link2_joint
      - link3_joint
      - link4_joint
      - link5_joint
      - link6_joint
      - link7_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
left_controller:
  ros__parameters:
    joints:
      - left_z_joint
      - left_x_joint
      - left_yaw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_controller:
  ros__parameters:
    joints:
      - right_z_joint
      - right_x_joint
      - right_yaw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity