wheel:
  LF:
    joint: [0.20286, 0.2023, -0.012411, -1.5708, 0, 0]
    fdir1: 1 -1 0

  RF:
    joint: [0.20286, -0.2023, -0.012411, -1.5708, 0, 0]
    fdir1: 1 1 0

  RB:
    joint: [-0.20286, -0.2023, -0.012411, -1.5708, 0, 0]
    fdir1: 1 -1 0

  LB:
    joint: [-0.20286, 0.2023, -0.012411, -1.5708, 0, 0]
    fdir1: 1 1 0

boom:
  link1:
    type: revolute
    joint: [0, 0, 0.0715, 0, 0, 0]
    axis: [0, 0, 1]
    limits: [-0.7854, 0.7854]
    inertial: [-0.000941, 0.005367, 0.0733]
    mass: 1.17054
    inertia: [0.005224, 0.000001, 0.000036, 0.005534, -0.000205, 0.004345]
  
  link2:
    type: revolute
    joint: [0, 0, 0.118, -1.5708, -1.0472, 0]
    axis: [0, 0, 1]
    limits: [-1E-06, 2.0944]
    inertial: [0.001243, -0.205517, -0.004229]
    mass: 1.37833
    inertia: [0.026143, -0.00183, 0.000127, 0.002503, 0.000050, 0.02504]
  
  link3:
    type: revolute
    joint: [0, -0.36, 0, 0, 0, 1.0472]
    axis: [0, 0, 1]
    limits: [-2.618, 1E-06]
    inertial: [0.124814, -0.008956, -0.000451]
    mass: 1.58588
    inertia: [0.001743, 0.000005, -0.000098, 0.004400, 0.000018, 0.004198]
  
  link4:
    type: revolute
    joint: [0.152, -0.003, 0, 1.5708, 0, 0]
    axis: [0, 0, 1]
    limits: [-0.4, 0.4]
    inertial: [0.036944, -0.000149, 0.001115]
    mass: 0.139812
    inertia: [0.000232, 0, 0.000007, 0.000195, 0, 0.000157]
  
  link5:
    type: revolute
    joint: [0.0756, 0, 0, 0, 1.5708, 0]
    axis: [0, 0, 1]
    limits: [-1.5709, 1.5709]
    inertial: [6E-06, 1.1E-05, 0.037589]
    mass: 0.528241
    inertia: [0.001034, 0.000009, -0.000001, 0.000977, -0.000001, 0.000568]
  
  link6:
    type: revolute
    joint: [0, 0, 0.1614, -1.6081, -1.5708, 0.037258]
    axis: [0, 0, 1]
    limits: [-1.8, 1.8]
    inertial: [0.005373, -0.001981, 2E-06]
    mass: 0.159991
    inertia: [0.000102, -0.000003, 0, 0.000146, 0, 0.000080]
  
  link7:
    type: revolute
    joint: [0.06955, 0, 0, 1.5708, 0, 1.5708]
    axis: [0, 0, 1]
    limits: [-6.28, 6.28]
    inertial: [0, 0, 0.006021]
    mass: 0.007071
    inertia: [0.000001, 0, 0, 0.000001, 0, 0.000001]

left:
  z:
    type: prismatic
    joint: [0.0633, 0.2075, 0.20311, 0, 0, 0]
    axis: [0, 0, 1]
    limits: [-1E-06, 0.08969]
    inertial: [-0.058037, 0.007699, 0.062634]
    mass: 2.06473
    inertia: [0.007718, 0.000177, 0.000195, 0.028724, 0.000010, 0.024449]
  
  x:
    type: prismatic
    joint: [-0.221, 0.0325, 0.144, 0, 0, 0]
    axis: [1, 0, 0]
    limits: [-1E-06, 0.3096]
    inertial: [0.161562, -0.055708, -0.018456]
    mass: 0.814767
    inertia: [0.000786, 0.000300, 0.001781, 0.026338, -0.000026, 0.026443]
  
  yaw:
    type: revolute
    joint: [0.4435, -0.0583, -0.0075, 0, 0, 0]
    axis: [0, 0, 1]
    limits: [-2.0944, 2.0944]
    inertial: [0.063197, -2.2E-05, -0.031301]
    mass: 0.06449
    inertia: [0.000069, 0, 0.000049, 0.000137, 0, 0.000086]

right:
  z:
    type: prismatic
    joint: [0.0658, -0.2075, 0.20311, 0, 0, 0]
    axis: [0, 0, 1]
    limits: [-1E-06, 0.08969]
    inertial: [-0.055178, -0.004026, 0.059103]
    mass: 1.69853
    inertia: [0.005215, -0.000469, -0.000041, 0.024571, -0.000786, 0.021373]
  
  x:
    type: prismatic
    joint: [-0.2481, -0.032, 0.144, 0, 0, 0]
    axis: [1, 0, 0]
    limits: [-1E-06, 0.3096]
    inertial: [0.205338, 0.052611, -0.020548]
    mass: 0.603922
    inertia: [0.000591, -0.000686, 0.001355, 0.021109, 0.000065, 0.021222]
  
  yaw:
    type: revolute
    joint: [0.4435, 0.0583, -0.0055, 0, 0, 0.018823]
    axis: [0, 0, 1]
    limits: [-2.0944, 2.0944]
    inertial: [0.063197, 2.2E-05, -0.033301]
    mass: 0.06449
    inertia: [0.000069, 0, 0.000049, 0.000137, 0, 0.000086]
